### PR TITLE
Edit "Documentation"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/185)

### CODE REVIEW

**Comment by funkill** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

<sup>**[src/documentation.md, line 3 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsL5kxuByEINd6XSDY7)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L3)):</sup>
"Она" лишнее

---

<sup>**[src/documentation.md, line 161 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsL9QEfSqOIZ4zCJPID)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L161)):</sup>

> Раздел `Examples`

Возможно стоит начинать описание разделов "Panics", "Safety" и "Failures" подобным образом?

---

<sup>**[src/documentation.md, line 229 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLB8AgAKSJtAO7UXOu)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L229)):</sup>
в чём-нибудь подобном

---

<sup>**[src/documentation.md, line 268 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLCFO9QTZtOszdrFxR)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L268)):</sup>
Некоторая документация.

---

<sup>**[src/documentation.md, line 275 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLCUNIHLO4CGgErF77)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L275)):</sup>
Некоторая документация.

---

<sup>**[src/documentation.md, line 400 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLG9HGVqMsZqQfyh4B)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L400)):</sup>
Возможно последнее предложение стоит как-то изменить? Мне в голову пока что не приходит хороший вариант, но в текущем варианте, как бы спотыкаешься, дочитывая предложение до конца.

---

<sup>**[src/documentation.md, line 414 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEDjIXks4DT9D9khX)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L414)):</sup>
неё

---

<sup>**[src/documentation.md, line 437 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEMDWpdsxGcUKBI3n)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L437)):</sup>
Дублируется "что"

---

<sup>**[src/documentation.md, line 444 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEZyI7-ry5LLMhG6z)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L444)):</sup>
ещё

---

<sup>**[src/documentation.md, line 458 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEfjfRKnGb8aAnr4x)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L458)):</sup>
Приведённый ... распространённое ...

---

<sup>**[src/documentation.md, line 540 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLFDjuvLX-bqOIPydw)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L540)):</sup>
Дублируется "настроек"

---

<sup>**[src/documentation.md, line 569 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLFZEHKSL0RVsptPB1)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L569)):</sup>
Возможно "который генерирует `rustdoc`"?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/185)

**Comment by mkpankov** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

<sup>**[src/documentation.md, line 3 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsL5kxuByEINd6XSDY7)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L3)):</sup>
Done.

---

<sup>**[src/documentation.md, line 161 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsL9QEfSqOIZ4zCJPID)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L161)):</sup>
Done.

---

<sup>**[src/documentation.md, line 229 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLB8AgAKSJtAO7UXOu)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L229)):</sup>
Done.

---

<sup>**[src/documentation.md, line 268 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLCFO9QTZtOszdrFxR)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L268)):</sup>
Done.

---

<sup>**[src/documentation.md, line 275 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLCUNIHLO4CGgErF77)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L275)):</sup>
Done.

---

<sup>**[src/documentation.md, line 400 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLG9HGVqMsZqQfyh4B)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L400)):</sup>
Попробую.

---

<sup>**[src/documentation.md, line 414 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEDjIXks4DT9D9khX)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L414)):</sup>
Done.

---

<sup>**[src/documentation.md, line 437 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEMDWpdsxGcUKBI3n)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L437)):</sup>
Done.

---

<sup>**[src/documentation.md, line 444 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEZyI7-ry5LLMhG6z)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L444)):</sup>
Done.

---

<sup>**[src/documentation.md, line 458 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLEfjfRKnGb8aAnr4x)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L458)):</sup>
Done.

---

<sup>**[src/documentation.md, line 540 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLFDjuvLX-bqOIPydw)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L540)):</sup>
Done.

---

<sup>**[src/documentation.md, line 569 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/185#-JsLFZEHKSL0RVsptPB1)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c68b82f7956602dd522a2f0447e00b97a4217923/src/documentation.md#L569)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/185)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/185)

**Comment by mkpankov** [comment]
Сливаю т.к. замечание исправлено, но ответ от автора замечания не получен

**Pull request merged**
