### PR TITLE
Properly fix anchor links

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/128)

### CODE REVIEW

**Comment by mkpankov** [comment]
Fix #119

**Comment by kgv** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/primitive-types.md, line 46 [r3]](https://reviewable.io:443/reviews/kgv/rust_book_ru/128#-JqsABY-JiY2l-pxhjRn)** ([raw file](https://github.com/kgv/rust_book_ru/blob/d68c5d6de06b7ebc7e665e2700cfdc1efc099de5/src/primitive-types.md#L46)):</sup>
`<a name="#numeric-types"></a>` -> `<a name="numeric-types"></a>`

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/128)

**Comment by kgv** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- src/attributes.md @ r1
- src/ffi.md @ r1
- src/glossary.md @ r1
- src/macros.md @ r3
- src/mutability.md @ r1
- src/primitive-types.md @ r1
- src/references-and-borrowing.md @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/128)

**Comment by kgv** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- src/primitive-types.md @ r4

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/128)

**Pull request merged**
