### PR TITLE
Update vectors.md

### PR DESCRIPTION
**Pull request by kgv**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/149)

### CODE REVIEW

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[src/vectors.md, line 3 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/149#-JrIam8er_jmU5mW_LBQ)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0b682aaa4081a8dbd61739a82ebc265f6b67f5c8/src/vectors.md#L3)):</sup>
...или, по-другому, ...

---

<sup>**[src/vectors.md, line 5 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/149#-JrIas8Hw59TqiRDvGMs)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0b682aaa4081a8dbd61739a82ebc265f6b67f5c8/src/vectors.md#L5)):</sup>
Вектор всегда размещает

или 

Вектора всегда размещают

---

<sup>**[src/vectors.md, line 33 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/149#-JrIayKIHhW4XNCf1xJT)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0b682aaa4081a8dbd61739a82ebc265f6b67f5c8/src/vectors.md#L33)):</sup>
отсчитываются

---

<sup>**[src/vectors.md, line 35 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/149#-JrIb2ogsXnOUiTFoZxZ)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0b682aaa4081a8dbd61739a82ebc265f6b67f5c8/src/vectors.md#L35)):</sup>
Как насчёт "Обход"?

---

<sup>**[src/vectors.md, line 37 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/149#-JrIb6YFG2NfL9a4tLfj)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0b682aaa4081a8dbd61739a82ebc265f6b67f5c8/src/vectors.md#L37)):</sup>
"обходить его элементы", соответственно

---

<sup>**[src/vectors.md, line 56 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/149#-JrIbDLLj6nfpfef5X5W)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0b682aaa4081a8dbd61739a82ebc265f6b67f5c8/src/vectors.md#L56)):</sup>
в документации API

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/149)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.
Reviewed files:
- src/vectors.md @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/149)

**Comment by kgv** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/vectors.md, line 35 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/149#-JrIb2ogsXnOUiTFoZxZ)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0b682aaa4081a8dbd61739a82ebc265f6b67f5c8/src/vectors.md#L35)):</sup>
Итерирование нравится больше, мне кажестя это не критично. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/149)

**Comment by mkpankov** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- src/vectors.md @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/149)

**Pull request merged**
