### PR TITLE
Fix "Is"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/214)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/closures.md, line 60 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/214#-JtZyfXJzuZhO4Xy1JgK)** ([raw file](https://github.com/kgv/rust_book_ru/blob/28e57af5bb454b62497f954c658351538b7ba932/src/closures.md#L60)):</sup>
нагляднее

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/214)

**Comment by mkpankov** [comment]
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

<sup>**[src/closures.md, line 60 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/214#-JtZyfXJzuZhO4Xy1JgK)** ([raw file](https://github.com/kgv/rust_book_ru/blob/28e57af5bb454b62497f954c658351538b7ba932/src/closures.md#L60)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/214)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/214)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/214)

**Comment by jiumx60rus** [comment]
Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/214)

**Pull request merged**
