### PR TITLE
Edit and bring up-to-date "Traits"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/245)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/traits.md, line 170 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/245#-JwJKpy7PMFhXt91gfyk)** ([raw file](https://github.com/kgv/rust_book_ru/blob/ada82656f8fdcd03ac0b6d940407c151fe8120b9/src/traits.md#L170)):</sup>
«Глупо» же.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/245)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/traits.md, line 170 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/245#-JwJKpy7PMFhXt91gfyk)** ([raw file](https://github.com/kgv/rust_book_ru/blob/ada82656f8fdcd03ac0b6d940407c151fe8120b9/src/traits.md#L170)):</sup>
В русском распространено "это смешно"

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/245)

**Comment by suhr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/traits.md, line 170 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/245#-JwJKpy7PMFhXt91gfyk)** ([raw file](https://github.com/kgv/rust_book_ru/blob/ada82656f8fdcd03ac0b6d940407c151fe8120b9/src/traits.md#L170)):</sup>
У него другой смысл.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/245)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/traits.md, line 170 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/245#-JwJKpy7PMFhXt91gfyk)** ([raw file](https://github.com/kgv/rust_book_ru/blob/ada82656f8fdcd03ac0b6d940407c151fe8120b9/src/traits.md#L170)):</sup>
Нормальный у  него смысл, здесь как раз подходит

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/245)

**Comment by suhr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/traits.md, line 170 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/245#-JwJKpy7PMFhXt91gfyk)** ([raw file](https://github.com/kgv/rust_book_ru/blob/ada82656f8fdcd03ac0b6d940407c151fe8120b9/src/traits.md#L170)):</sup>
Не соглашусь. «Это смешно» больше подходит для чего-то ridiculous, чем для чего-то silly.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/245)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/traits.md, line 170 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/245#-JwJKpy7PMFhXt91gfyk)** ([raw file](https://github.com/kgv/rust_book_ru/blob/ada82656f8fdcd03ac0b6d940407c151fe8120b9/src/traits.md#L170)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/245)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/245)

**Pull request merged**
