### PR TITLE
Edit "Installing Rust"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/174)

### CODE REVIEW

**Comment by kgv** [comment]
Думаю стоит сразу обновлять до текущей ревизии. С момента перевода были сделаны изменения.

---

Review status: 0 of 1 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/installing-rust.md, line 92 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-Jrt5xXLmkcMJWyeKbXy)** ([raw file](https://github.com/kgv/rust_book_ru/blob/d357029362c21b0add33246b955e807edbe4afc1/src/installing-rust.md#L92)):</sup>
Кстати, "Rustaceans" насколько я понял это игра слов и на русский должна переводиться как Растообразные. В ру комьюнити вроде как прижилось "Растаманы". Еще мне очень понравилась версия "Растишки" XD.
Как-то будем это отражать?

---

<sup>**[src/installing-rust.md, line 105 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-Jrt5ceCWDduhRBbAB-9)** ([raw file](https://github.com/kgv/rust_book_ru/blob/d357029362c21b0add33246b955e807edbe4afc1/src/installing-rust.md#L105)):</sup>
mibbit -> mibbit_ru

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by mkpankov** [comment]
Проверил: 
`➜  rust git:(master) git diff master 2de6515de8cf3298a9f17f0c520c491f56b017b7 -- src/doc/trpl/installing-rust.md`

Всё соответствует (изменения от original commit до мастера в этом переводе есть)

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/installing-rust.md, line 92 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-Jrt5xXLmkcMJWyeKbXy)** ([raw file](https://github.com/kgv/rust_book_ru/blob/d357029362c21b0add33246b955e807edbe4afc1/src/installing-rust.md#L92)):</sup>
Надо думать, создал [задачу](https://github.com/kgv/rust_book_ru/issues/176)

---

<sup>**[src/installing-rust.md, line 105 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-Jrt5ceCWDduhRBbAB-9)** ([raw file](https://github.com/kgv/rust_book_ru/blob/d357029362c21b0add33246b955e807edbe4afc1/src/installing-rust.md#L105)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by mkpankov** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by kgv** [comment]
[Отсюда](https://raw.githubusercontent.com/rust-lang/rust/master/src/doc/trpl/installing-rust.md)

Например:

оригинал:

> If you're on Windows, please download the appropriate [installer][install-page].
> 
> [install-page]: http://www.rust-lang.org/install.html

у нас:

> Если же вы используете Windows, то, пожалуйста, скачайте один из установочных
> пакетов: [32-битный][win32] или [64-битный][win64] и запустите его.
>  
> [win32]: https://static.rust-lang.org/dist/rust-1.0.0-i686-pc-windows-gnu.msi
> [win64]: https://static.rust-lang.org/dist/rust-1.0.0-x86_64-pc-windows-gnu.msi

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by mkpankov** [comment]
А, я наоборот посмотрел, понял, сейчас поисправляю

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/installing-rust.md, line 78 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-JrtPCXSkKS56Y7_zn7b)** ([raw file](https://github.com/kgv/rust_book_ru/blob/7cdcc54b61b7978ebfcc73b448f66642fbbb3107/src/installing-rust.md#L78)):</sup>
Тут в nightly сделали изменения, не соответствующие действительности:

```
@@ -71,10 +72,11 @@ If you've got Rust installed, you can open up a shell, and type this:
 $ rustc --version
```

-You should see the version number, commit hash, commit date and build date:
+You should see the version number, commit hash, and commit date. If you just
+installed version 1.0.0, you should see:

``` bash
-rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
+rustc 1.0.0 (a59de37e9 2015-05-13)
```

 If you did, Rust has been installed successfully! Congrats!

```

У меня выводится 

```

➜  ~  rustc --version
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

```

т.е. дата коммита и дата сборки.

Не понимаю, почему в тексте изменили это место.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)
<!-- Sent from Reviewable.io -->
```

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/installing-rust.md, line 78 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-JrtPCXSkKS56Y7_zn7b)** ([raw file](https://github.com/kgv/rust_book_ru/blob/7cdcc54b61b7978ebfcc73b448f66642fbbb3107/src/installing-rust.md#L78)):</sup>
Ещё и разметка уплыла, прошу прощения

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by kgv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/installing-rust.md, line 81 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-JrtPCXSkKS56Y7_zn7b)** ([raw file](https://github.com/kgv/rust_book_ru/blob/7cdcc54b61b7978ebfcc73b448f66642fbbb3107/src/installing-rust.md#L81)):</sup>
у меня тоже информация о сборке выводится.
Думаю, оставляем `rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)`

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by kgv** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/installing-rust.md, line 89 [r3]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-JrtZADq3pNyCnSrqGyO)** ([raw file](https://github.com/kgv/rust_book_ru/blob/e9c399aeca7d2d7f88b0cfb464ec8b14ac55a083/src/installing-rust.md#L89)):</sup>
каталог или директория как и в hello-world

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/installing-rust.md, line 89 [r3]](https://reviewable.io:443/reviews/kgv/rust_book_ru/174#-JrtZADq3pNyCnSrqGyO)** ([raw file](https://github.com/kgv/rust_book_ru/blob/e9c399aeca7d2d7f88b0cfb464ec8b14ac55a083/src/installing-rust.md#L89)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Comment by kgv** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/174)

**Pull request merged**
