### PR TITLE
 Обновление Bibliography

### LINKED ISSUE #325: Обновить Bibliography
http://doc.rust-lang.org/nightly/book/bibliography.html

Старое название: `academic-research.md`

### PR DESCRIPTION
**Pull request by vessd**
Fix #325
Описание пока решил оставить, поскольку там достаточно терминов, значение которых мне не понятно даже со словарем.

[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/339)

### CODE REVIEW

**Comment by mkpankov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/bibliography.md, line 3 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/339#-K7mbwsjOirbwYH3V09f:-K7mbwskNkwLPqIai2Iq:-1590799227) ([raw file](https://github.com/kgv/rust_book_ru/blob/328394701647d939a6e265c783691c50b7e7c37d/src/bibliography.md#L3)):_
Это - список материалов, имеющих отношение к Rust.

---

_[src/bibliography.md, line 36 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/339#-K7mc2RiFha9zaciuBsw:-K7mc2RiFha9zaciuBsx:-498191740) ([raw file](https://github.com/kgv/rust_book_ru/blob/328394701647d939a6e265c783691c50b7e7c37d/src/bibliography.md#L36)):_
Epoch

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/339)_

**Comment by vessd** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/bibliography.md, line 3 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/339#-K7mbwsjOirbwYH3V09f:-K7o201oebIw4uY50I83:-499146009) ([raw file](https://github.com/kgv/rust_book_ru/blob/328394701647d939a6e265c783691c50b7e7c37d/src/bibliography.md#L3)):_
Done.

---

_[src/bibliography.md, line 36 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/339#-K7mc2RiFha9zaciuBsw:-K7o20hFla0fnzMxhcgf:-1378927682) ([raw file](https://github.com/kgv/rust_book_ru/blob/328394701647d939a6e265c783691c50b7e7c37d/src/bibliography.md#L36)):_
ошибка оригинала?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/339)_

**Comment by mkpankov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/bibliography.md, line 36 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/339#-K7mc2RiFha9zaciuBsw:-K7rhKncauQCuR_8xG8M:1562853633) ([raw file](https://github.com/kgv/rust_book_ru/blob/328394701647d939a6e265c783691c50b7e7c37d/src/bibliography.md#L36)):_
Да - в статье раздел "5.2.3 Epoch-based reclamation"

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/339)_

**Comment by mkpankov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/339)_

**Comment by vessd** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/bibliography.md, line 36 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/339#-K7mc2RiFha9zaciuBsw:-K7ynNFZibOBAlNKO4p-:-499146009) ([raw file](https://github.com/kgv/rust_book_ru/blob/328394701647d939a6e265c783691c50b7e7c37d/src/bibliography.md#L36)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/339)_

**Pull request merged**
