### PR TITLE
Edit "Iterators"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/186)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/iterators.md, line 75 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/186#-Js7zaPmRvsaxTca9_zi)** ([raw file](https://github.com/kgv/rust_book_ru/blob/58a92671daec7ced2c17c8d1bcb896a6d64573e4/src/iterators.md#L75)):</sup>
«Яснее»?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/186)

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/iterators.md, line 75 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/186#-Js7zaPmRvsaxTca9_zi)** ([raw file](https://github.com/kgv/rust_book_ru/blob/58a92671daec7ced2c17c8d1bcb896a6d64573e4/src/iterators.md#L75)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/186)

**Comment by mkpankov** [comment]
Bump

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/186)

**Pull request merged**
