### PR TITLE
Improve quotes!

### LINKED ISSUE #208: Типографские кавычки в тексте
Либо их rustbook должен произвоить из машинописных, либо надо заменить их скриптом вручную.

### PR DESCRIPTION
**Pull request by mkpankov**
Close #208 

[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/210)

### CODE REVIEW

**Comment by suhr** [comment]
<sup>**[src/documentation.md, line 171 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/210#-JtKyraGH86U9WlRwekb)** ([raw file](https://github.com/kgv/rust_book_ru/blob/f8cba7e8ba0e4d8dba86a28011e24f72d1fbfe7e/src/documentation.md#L171)):</sup>
Ненене, здесь уже порча кода.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/210)

**Comment by suhr** [comment]
Reviewed 39 of 42 files at r1.
Review status: 39 of 42 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/README.md, line 94 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/210#-JtKxXQ2em7V03g0S0Ad)** ([raw file](https://github.com/kgv/rust_book_ru/blob/f8cba7e8ba0e4d8dba86a28011e24f72d1fbfe7e/src/README.md#L94)):</sup>
Кавычки лучше выносить из ссылки. Вот так: `«[Стек и Куча][heap]»`.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/210)

**Comment by mkpankov** [comment]
Review status: 28 of 44 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

<sup>**[src/documentation.md, line 171 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/210#-JtKyraGH86U9WlRwekb)** ([raw file](https://github.com/kgv/rust_book_ru/blob/f8cba7e8ba0e4d8dba86a28011e24f72d1fbfe7e/src/documentation.md#L171)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/210)

**Comment by mkpankov** [comment]
Вот чем руководствовался:

http://writercenter.ru/blog/grammar/kavychki-gospoda-kavychki.html

**Comment by suhr** [comment]
Reviewed 2 of 14 files at r2.
Review status: 30 of 44 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/README.md, line 94 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/210#-JtL2cfX1KEu9wmMRCM3)** ([raw file](https://github.com/kgv/rust_book_ru/blob/eb9e0e9fc94a011e5c957398c8b02045912bf851/src/README.md#L94)):</sup>
Отлично, но это не едиственное подобное место.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/210)

**Comment by mkpankov** [comment]
Review status: 28 of 43 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/README.md, line 94 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/210#-JtL2cfX1KEu9wmMRCM3)** ([raw file](https://github.com/kgv/rust_book_ru/blob/eb9e0e9fc94a011e5c957398c8b02045912bf851/src/README.md#L94)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/210)

**Comment by suhr** [comment]
Reviewed 2 of 42 files at r1, 11 of 14 files at r2, 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/210)

**Pull request merged**
