### PR TITLE
Update "Unsafe"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/260)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[src/unsafe.md, line 4 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJPY1aSHQB-PUD3gxg)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L4)):</sup>

> проверки безопасности очень консервативны

Здесь скорее имеется в виду «осторожны».

---

<sup>**[src/unsafe.md, line 60 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJVsJ58R4WxiFOgSTN)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L60)):</sup>

> but they don’t qualify as unsafe specifically

Другой смысл же.

---

<sup>**[src/unsafe.md, line 67 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJXMSXIzO7_wCIUjO2)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L67)):</sup>
«Гонка данных»? Как именно принято переводит этот термин?

---

<sup>**[src/unsafe.md, line 97 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJYSZfd9WH4NX3f4Sj)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L97)):</sup>
Всего три.

---

<sup>**[src/unsafe.md, line 105 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJZ--JcTwsou0vi9Yj)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L105)):</sup>
«Небезопасность не означает принятие компилятором любого кода. Но она позволяет писать вещи, которые _нарушают_ некоторые из правил».

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/260)

**Comment by mkpankov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[src/unsafe.md, line 4 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJPY1aSHQB-PUD3gxg)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L4)):</sup>
Done.

---

<sup>**[src/unsafe.md, line 60 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJVsJ58R4WxiFOgSTN)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L60)):</sup>
По-моему всё нормально: "Но они не считаются именно что небезопасными".

---

<sup>**[src/unsafe.md, line 67 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJXMSXIzO7_wCIUjO2)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L67)):</sup>
Done.

---

<sup>**[src/unsafe.md, line 97 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJYSZfd9WH4NX3f4Sj)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L97)):</sup>
Done.

---

<sup>**[src/unsafe.md, line 105 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJZ--JcTwsou0vi9Yj)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L105)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/260)

**Comment by suhr** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/unsafe.md, line 60 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJVsJ58R4WxiFOgSTN)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L60)):</sup>
Согласись, есть разница между «не считаются именно что небезопасными» и «да не очень-то они и опасны».

---

<sup>**[src/unsafe.md, line 105 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJZ--JcTwsou0vi9Yj)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L105)):</sup>
Не совсем.  Курсив всё ещё на «некоторые».

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/260)

**Comment by mkpankov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/unsafe.md, line 60 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJVsJ58R4WxiFOgSTN)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L60)):</sup>
Done.

---

<sup>**[src/unsafe.md, line 105 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/260#-JxJZ--JcTwsou0vi9Yj)** ([raw file](https://github.com/kgv/rust_book_ru/blob/2c4894289d5b3fbfe1380ab7d5daa0b62ebee791/src/unsafe.md#L105)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/260)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/260)

**Pull request merged**
