### PR TITLE
Edit "Concurrency"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/187)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/concurrency.md, line 15 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/187#-Js8-V1zJsExUa_bziN8)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0fbb712ef432e1275266419327fa7507a58ac750/src/concurrency.md#L15)):</sup>
«Rust — достаточно низкоуровневый язык, поэтому...».

---

<sup>**[src/concurrency.md, line 25 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/187#-Js8-pbL6jIeSmwBaEky)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0fbb712ef432e1275266419327fa7507a58ac750/src/concurrency.md#L25)):</sup>
Запятая после «В связи с этим».

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/187)

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/concurrency.md, line 15 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/187#-Js8-V1zJsExUa_bziN8)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0fbb712ef432e1275266419327fa7507a58ac750/src/concurrency.md#L15)):</sup>
Done.

---

<sup>**[src/concurrency.md, line 25 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/187#-Js8-pbL6jIeSmwBaEky)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0fbb712ef432e1275266419327fa7507a58ac750/src/concurrency.md#L25)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/187)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/187)

**Comment by mkpankov** [comment]
Bump

**Comment by kgv** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/concurrency.md, line 25 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/187#-Js8-pbL6jIeSmwBaEky)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0fbb712ef432e1275266419327fa7507a58ac750/src/concurrency.md#L25)):</sup>
[Запятая не нужна](http://www.gramota.ru/spravka/punctum/58_792). Это союз, но придаточное предложение у нас просто отделено точкой.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/187)

**Comment by kgv** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/187)

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/concurrency.md, line 25 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/187#-Js8-pbL6jIeSmwBaEky)** ([raw file](https://github.com/kgv/rust_book_ru/blob/0fbb712ef432e1275266419327fa7507a58ac750/src/concurrency.md#L25)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/187)

**Comment by kgv** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/187)

**Comment by mkpankov** [comment]
Я не понимаю что здесь делать, сливаем?

**Pull request merged**
