### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### kgv/rust_book_ru now has a Chat Room on Gitter

@mkpankov has just created a chat room. You can visit it here: [https://gitter.im/kgv/rust_book_ru](https://gitter.im/kgv/rust_book_ru?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/kgv/rust_book_ru?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by mkpankov** [comment]
@kgv @funkill вы не против добавления этой ссылки?

**Comment by funkill** [comment]
Я не против

**Comment by mkpankov** [comment]
Она в gitbook / rustbook нормально выглядеть будет?

**Comment by funkill** [comment]
На gitbook со 100% увереностью не скажу, но должна нормально выглядеть. rustbook нормально обрабатывает

**Comment by kgv** [comment]
:+1:

**Pull request merged**
