### PR TITLE
Translate lang items

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/161)

### CODE REVIEW

**Comment by kgv** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- src/lang-items.md @ r1

---

<sup>**[src/lang-items.md, line 4 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/161#-JriR4D3PNBv-oaR4nGx)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6d3d19dbb6f26f6bf6ba5810535e435ba2688d85/src/lang-items.md#L4)):</sup>

> , но сами по себе элементы языка имеют нестабильный интерфейс.

Как предложение, но не критично.

---

<sup>**[src/lang-items.md, line 6 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/161#-JriRPgdFTijKynWjN-s)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6d3d19dbb6f26f6bf6ba5810535e435ba2688d85/src/lang-items.md#L6)):</sup>
определить -> определять

---

<sup>**[src/lang-items.md, line 66 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/161#-JriSied6HhLGGYS4owo)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6d3d19dbb6f26f6bf6ba5810535e435ba2688d85/src/lang-items.md#L66)):</sup>
Часто встречал термин "раскрутка стека", "размотка стека" ни разу.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/161)

**Comment by kgv** [comment]
В SUMMARY.md не переведена эта глава.

---

Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/161)

**Comment by mkpankov** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/lang-items.md, line 6 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/161#-JriRPgdFTijKynWjN-s)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6d3d19dbb6f26f6bf6ba5810535e435ba2688d85/src/lang-items.md#L6)):</sup>
Done.

---

<sup>**[src/lang-items.md, line 66 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/161#-JriSied6HhLGGYS4owo)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6d3d19dbb6f26f6bf6ba5810535e435ba2688d85/src/lang-items.md#L66)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/161)

**Comment by kgv** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- src/lang-items.md @ r2
- SUMMARY.md @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/161)

**Pull request merged**
