### PR TITLE
Edit ownership

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/227)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/lifetimes.md, line 34 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3IDszhEzaBLYowUON)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L34)):</sup>
Кавычки стоят несколько неудачно, так как борьба-то настоящая.

---

<sup>**[src/lifetimes.md, line 211 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3J1xgGb0pYRR8B7Nr)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L211)):</sup>
-//- «static» — особенное.

---

<sup>**[src/ownership.md, line 34 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3KGpVlXTSIx9CSQIS)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/ownership.md#L34)):</sup>
-//-

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/227)

**Comment by mkpankov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/lifetimes.md, line 34 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3IDszhEzaBLYowUON)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L34)):</sup>
Но выражение всё-таки фигуральное - и в оригинале оно тоже в кавычках

---

<sup>**[src/lifetimes.md, line 211 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3J1xgGb0pYRR8B7Nr)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L211)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/227)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/lifetimes.md, line 34 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3IDszhEzaBLYowUON)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L34)):</sup>
В оригинале «Many new users to Rust experience something we like to call ‘fighting with the borrow checker’, where the Rust compiler refuses to compile a program that the author thinks is valid». Т.е кавычки стоят по другому поводу.
А борьба-то идёт не шуточная, любой начинающий программист на расте подтвердит.
Думаю, здесь можно приблизить перевод к оригиналу.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/227)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/lifetimes.md, line 34 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3IDszhEzaBLYowUON)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L34)):</sup>
Мне не нравится неуклюжее "испытывают то, что нам нравится называть "борьбой с проверкой заимствования". Если у тебя есть варианты получше, предлагай, пожалуйста.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/227)

**Comment by suhr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/lifetimes.md, line 34 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3IDszhEzaBLYowUON)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L34)):</sup>
Многие пользователи Rust занимаются тем, что мы зовём «борьбой с проверкой заимствования»

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/227)

**Comment by mkpankov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/lifetimes.md, line 34 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/227#-Ju3IDszhEzaBLYowUON)** ([raw file](https://github.com/kgv/rust_book_ru/blob/c20819f7a41f80b1650b1738663d6bf54abd992d/src/lifetimes.md#L34)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/227)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/227)

**Pull request merged**
