### PR TITLE
Continue macros

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/127)

### CODE REVIEW

**Comment by jiumx60rus** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/macros.md, line 537 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjVK69_tpRQIj_tfAh)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L537)):</sup>
Последующем коде модуля

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/127)

**Comment by jiumx60rus** [comment]
Оу оно сюда пришло)

**Comment by jiumx60rus** [comment]
Review status: 0 of 1 files reviewed, 10 unresolved discussions, all commit checks successful.

---

<sup>**[src/macros.md, line 557 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjXGKmevG6pU7RRLpd)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L557)):</sup>
то будут загружены все

---

<sup>**[src/macros.md, line 569 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjXq5SxTSSKmycHobd)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L569)):</sup>
видно

---

<sup>**[src/macros.md, line 572 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjXsV5QFXQ10uYwIAK)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L572)):</sup>
видно

---

<sup>**[src/macros.md, line 577 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjY8BO4EnWFulOUuSK)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L577)):</sup>
здесь видны

---

<sup>**[src/macros.md, line 580 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjXtnGC4q1WfDVFuT5)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L580)):</sup>
видно

---

<sup>**[src/macros.md, line 584 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjY8ya_eaLgtSVcvTU)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L584)):</sup>
здесь видны

---

<sup>**[src/macros.md, line 588 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjY9LKAz56zuNJJZrF)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L588)):</sup>
здесь видны

---

<sup>**[src/macros.md, line 592 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjY9dHuCtdh5dzX3B0)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L592)):</sup>
здесь видны

---

<sup>**[src/macros.md, line 595 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjY9wLTi9xAOHu3peC)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L595)):</sup>
здесь видны

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/127)

**Comment by jiumx60rus** [comment]
Review status: all files reviewed, 10 unresolved discussions, all commit checks successful.
Reviewed files:
- src/macros.md @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/127)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/macros.md, line 537 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjVK69_tpRQIj_tfAh)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L537)):</sup>
Done.

---

<sup>**[src/macros.md, line 557 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjXGKmevG6pU7RRLpd)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L557)):</sup>
"то" ничего не добавляет здесь, по-моему.

Неужели можно неправильно истолковать это место?

---

<sup>**[src/macros.md, line 569 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjXq5SxTSSKmycHobd)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L569)):</sup>
m1 - это макрос, не "видно" точно

По-моему здесь глагол не надо согласовывать, потому что он описывает список вещей, идущих после двоеточия (вещей много)

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/127)

**Comment by kgv** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/macros.md, line 568 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/127#-JqjXq5SxTSSKmycHobd)** ([raw file](https://github.com/kgv/rust_book_ru/blob/03847d0fdc1e8e04dff5bcbea747784a5bc57679/src/macros.md#L568)):</sup>
видны :+1: 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/127)

**Comment by kgv** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- src/macros.md @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/127)

**Pull request merged**
