### PR TITLE
Edit and bring up-to date the rest of "Syntax & Semantics"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/247)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/structs.md, line 55 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/247#-JwJImtjhNvvwDdPpm-J)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6200230131ebe5a39814833cff91537b4809e7e8/src/structs.md#L55)):</sup>
Опечатка.

---

<sup>**[src/structs.md, line 161 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/247#-JwJJW782C2zlOlH8tEM)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6200230131ebe5a39814833cff91537b4809e7e8/src/structs.md#L161)):</sup>

> Такое использование называется _новым типом_

Не слишком ли дословный перевод «newtype»?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/247)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/structs.md, line 55 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/247#-JwJImtjhNvvwDdPpm-J)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6200230131ebe5a39814833cff91537b4809e7e8/src/structs.md#L55)):</sup>
Done.

---

<sup>**[src/structs.md, line 161 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/247#-JwJJW782C2zlOlH8tEM)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6200230131ebe5a39814833cff91537b4809e7e8/src/structs.md#L161)):</sup>
Что ты предлагаешь?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/247)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/structs.md, line 161 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/247#-JwJJW782C2zlOlH8tEM)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6200230131ebe5a39814833cff91537b4809e7e8/src/structs.md#L161)):</sup>
Предлагаю вынести в отдельный issue этот вопрос.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/247)

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/structs.md, line 161 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/247#-JwJJW782C2zlOlH8tEM)** ([raw file](https://github.com/kgv/rust_book_ru/blob/6200230131ebe5a39814833cff91537b4809e7e8/src/structs.md#L161)):</sup>
Вынеси тогда. Это вообще старый текст, не я его писал и я его не редактирую в этом коммите

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/247)

**Pull request merged**
