### PR TITLE
Style fixes

### LINKED ISSUE #39: Todo ffi.md
https://github.com/kgv/rust_book_ru/blob/master/patch/ffi.md.patch
- [ ] so specifying it correctly is part of keeping the binding correct at runtime.
- [ ] Native dynamic libraries and frameworks are propagated to the final artifact boundary, while static libraries are not propagated at all.
- [ ] "nullable pointer optimization"

### PR DESCRIPTION
**Pull request by mkpankov**
Close #39

[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/104)

### CODE REVIEW

**Comment by kgv** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[effective-rust/ffi.md, line 524 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/104#-Jpzdsh-Y0oOLj8KDYiq)** ([raw file](https://github.com/kgv/rust_book_ru/blob/81230a3b180618f24721446cb8ac444b0fd5c538/effective-rust/ffi.md#L524)):</sup>
Обнуляемый для перевода "nullable"? мне кажется не совсем верно будет воспринят.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[effective-rust/ffi.md, line 524 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/104#-Jpzdsh-Y0oOLj8KDYiq)** ([raw file](https://github.com/kgv/rust_book_ru/blob/81230a3b180618f24721446cb8ac444b0fd5c538/effective-rust/ffi.md#L524)):</sup>
Почему?

Nullable - такой, который может иметь значение NULL. Т.е. потенциально может обнулиться. Т.е. обнуляемый.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by kgv** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[effective-rust/ffi.md, line 524 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/104#-Jpzdsh-Y0oOLj8KDYiq)** ([raw file](https://github.com/kgv/rust_book_ru/blob/81230a3b180618f24721446cb8ac444b0fd5c538/effective-rust/ffi.md#L524)):</sup>
Обнуляемый в моем понимании - не тот, который МОЖЕТ обнулиться, а тот, который БУДЕТ обнулен.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[effective-rust/ffi.md, line 524 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/104#-Jpzdsh-Y0oOLj8KDYiq)** ([raw file](https://github.com/kgv/rust_book_ru/blob/81230a3b180618f24721446cb8ac444b0fd5c538/effective-rust/ffi.md#L524)):</sup>
Хм, ну кроме этого я могу придумать "возможно обнуляемый указатель" или "указатель, который может быть нулевым". Хотя это громоздко уже получается.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by kgv** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[effective-rust/ffi.md, line 524 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/104#-Jpzdsh-Y0oOLj8KDYiq)** ([raw file](https://github.com/kgv/rust_book_ru/blob/81230a3b180618f24721446cb8ac444b0fd5c538/effective-rust/ffi.md#L524)):</sup>
"допускающий значение null" можно использовать. Хоть и достаточно грамоздко, но не вызывает двусмысленности.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by kgv** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- effective-rust/ffi.md @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by kgv** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- effective-rust/ffi.md @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[effective-rust/ffi.md, line 524 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/104#-Jpzdsh-Y0oOLj8KDYiq)** ([raw file](https://github.com/kgv/rust_book_ru/blob/81230a3b180618f24721446cb8ac444b0fd5c538/effective-rust/ffi.md#L524)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- effective-rust/ffi.md @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by kgv** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- effective-rust/ffi.md @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by mkpankov** [comment]
Не понимаю, почему `1 unresolved discussion`. Вроде нет новых комментариев. Всё нормально, сливаю?

**Comment by kgv** [comment]
У меня `0 unresolved discussion`. Баг наверно.

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/104)

**Comment by mkpankov** [comment]
Ох, ну и говно же этот новомодный Reviewable...

**Pull request merged**
