### PR TITLE
Edit "Error handling"

### PR DESCRIPTION
**Pull request by mkpankov**
[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/188)

### CODE REVIEW

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/error-handling.md, line 43 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/188#-Js7yOAk8Us2e94Lp33E)** ([raw file](https://github.com/kgv/rust_book_ru/blob/752cb69e6e003fd1ebf415c40c7719fec1cf6d8a/src/error-handling.md#L43)):</sup>
Или «существуют ошибки».

---

<sup>**[src/error-handling.md, line 308 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/188#-Js7yv2tEp8cvN2BeYjx)** ([raw file](https://github.com/kgv/rust_book_ru/blob/752cb69e6e003fd1ebf415c40c7719fec1cf6d8a/src/error-handling.md#L308)):</sup>
«Распакованное»? Здесь есть коллизия с упаковками.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/188)

**Comment by mkpankov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/error-handling.md, line 43 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/188#-Js7yOAk8Us2e94Lp33E)** ([raw file](https://github.com/kgv/rust_book_ru/blob/752cb69e6e003fd1ebf415c40c7719fec1cf6d8a/src/error-handling.md#L43)):</sup>
Done.

---

<sup>**[src/error-handling.md, line 308 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/188#-Js7yv2tEp8cvN2BeYjx)** ([raw file](https://github.com/kgv/rust_book_ru/blob/752cb69e6e003fd1ebf415c40c7719fec1cf6d8a/src/error-handling.md#L308)):</sup>
Так-то да, но "развёрнутое" будет хуже, да и из контекста вроде понятно

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/188)

**Comment by suhr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/error-handling.md, line 308 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/188#-Js7yv2tEp8cvN2BeYjx)** ([raw file](https://github.com/kgv/rust_book_ru/blob/752cb69e6e003fd1ebf415c40c7719fec1cf6d8a/src/error-handling.md#L308)):</sup>
Всё равно надо будет потом обсудить, как переводить `unwrapped`.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/188)

**Comment by mkpankov** [comment]
Bump

**Comment by mkpankov** [comment]
Сливаю т.к. замечания исправлены, но Acknowledge не получен

**Pull request merged**
