### PR TITLE
Add AUTHORS file.

### PR DESCRIPTION
**Pull request by kgv**
Предлагаю добавить файлик AUTHORS.md, где в алфавитном порядке будут расположены соавторы данной книги.

[Review on Reviewable](https://reviewable.io/reviews/kgv/rust_book_ru/107)

### CODE REVIEW

**Comment by suhr** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[README.md, line 30 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-JpzqxS6dgdjbdChPPxt)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/README.md#L30)):</sup>

> Хочется; хочу

Возможно, стоит чуть лучше это сформулировать?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by kgv** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[README.md, line 30 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-JpzqxS6dgdjbdChPPxt)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/README.md#L30)):</sup>
Например? По мне - так неплохо звучит.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[README.md, line 30 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-JpzqxS6dgdjbdChPPxt)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/README.md#L30)):</sup>
Моё предложение:

> Хочу поблагодарить моих родителей, Таню и Володю. ...
> 
> Также хочу выразить благодарность всем, кто принимал участие в создании этой книги.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[AUTHORS.md, line 4 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-Jq0z0M824HzYbHNb9uw)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/AUTHORS.md#L4)):</sup>
Есть ли смысл вносить сюда gitter-badger? Он будет благодарен упоминанию, конечно... :)

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- AUTHORS.md @ r1
- README.md @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[README.md, line 30 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-JpzqxS6dgdjbdChPPxt)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/README.md#L30)):</sup>
Ну или даже вот:

> Хочу поблагодарить моих родителей, Таню и Володю. ...
> 
> Также благодарю всех, кто принимал участие в создании этой книги.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by kgv** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[AUTHORS.md, line 4 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-Jq0z0M824HzYbHNb9uw)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/AUTHORS.md#L4)):</sup>
Ой, скопировал всех просто из списка коммитеров )))

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by kgv** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[README.md, line 30 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-JpzqxS6dgdjbdChPPxt)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/README.md#L30)):</sup>
Ааа, в смысле тавтологии... не заметил. Понял, поправлю.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by kgv** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- AUTHORS.md @ r2
- README.md @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by suhr** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[README.md, line 30 [r2]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-Jq3nFIqQh_T1dNNiJbC)** ([raw file](https://github.com/kgv/rust_book_ru/blob/d6f321e25d9a34c3abef3535e1cd6fb333b5bf31/README.md#L30)):</sup>
«**Таню** и **Володю**» же.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by kgv** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- README.md @ r3

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- AUTHORS.md @ r2
- README.md @ r2, r3

---

<sup>**[README.md, line 30 [r1]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-JpzqxS6dgdjbdChPPxt)** ([raw file](https://github.com/kgv/rust_book_ru/blob/8af678e0d5cfd16253d967059f7bb9f9ce2009dc/README.md#L30)):</sup>
Теперь когда на это обратили внимание, "Хочется" и "Хочу" действительно коробит. У меня "хочется" ассоциируется с чем-то неосознанным, да и с "хочется, но не буду".

Поэтому я предложил в последнем варианте выше в одном предложении вообще убрать выражение "хотения". Я думаю, так чище и лучше читается.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- AUTHORS.md @ r2
- README.md @ r3

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- README.md @ r4

---

<sup>**[README.md, line 27 [r4]](https://reviewable.io:443/reviews/kgv/rust_book_ru/107#-JqF-73pkLZSOBZYoB-_)** ([raw file](https://github.com/kgv/rust_book_ru/blob/4723669d96c39cab5543a7c15391ae5ea3d54ed2/README.md#L27)):</sup>
Выражаем

Я поясню: пассивный залог создаёт ощущение формализма и ненаправленности действия (кем выражается? кому?). Я это не с потолка взял (читал несколько книг по писательскому мастерству). Поэтому везде, где только можно, предпочитаю активный залог ("выражаем", т.е. "мы выражаем"), потому что это "оживляет" речь и читается, по-моему лучше.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- README.md @ r4

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Comment by mkpankov** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- README.md @ r5

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kgv/rust_book_ru/107)

**Pull request merged**
